### ISSUE TITLE
arbitrary instance, other instances

### ISSUE THREAD

**Issue by athanclark** [purescript-contrib/purescript-uint#7]
Hey there, would you be willing to add / accept a pull request that adds casual instances for typeclasses common in purescript, like quickcheck's Arbitrary, argonaut's EncodeJson / DecodeJson, possibly even generic-rep (through `Number`)? If you'd rather not due to inherited dependencies, I kindof understand, but it would be really beneficial because we can't write orphan instances, and this is such a fundamental type that I think it should have similar treatment to Maybe and Either - treated as a component of the language.

Anyway, please let me know, I'd love to submit the PR!

**Comment by zaquest** [comment]
Hello.

In general I would oppose those changes. I know these instances are good to have, but I just can't agree having these dependencies. However, since there's no better option, I guess we'll have to rely on optimizers to remove that dead code from production builds. That reminds me that PureScript has seemingly completely useless instance names. I wonder why have them if not to solve orphan instances issues...

In any case, I don't write PureScript these days, so if there's anyone in the community interested to take over the package, or to have write access to the repo, I would be glad to hand `purescript-uint` over to him. And that person can decide what's better in today's PureScript: lean dependencies or having instances of common classes.

I will accept the PR. Please consider taking over the package.

**Comment by athanclark** [comment]
I would love to take over the package - I use purescript all the time, and plan to support the ecosystem for a lot longer.
As far as DCO goes; most people use `purs bundle`, which doesn't do a perfect job, but there's currently work being done on a rollup module that does cool stuff like uncurrying and elimination of instance dictionary overhead. But anyway, I'll submit that PR as soon as I can!

**Comment by zaquest** [comment]
> I would love to take over the package

Great, you should have write access now. We'll need to figure out how to proceed with Pursuit, if write access to this repo is enough for publishing new versions then great. If not could you please investigate what it will take for you to be able to publish to Pursuit/Bower?

**Comment by athanclark** [comment]
It looks like I have everything I need to publish new revisions - I just released v4.1.0. Thank you so much!
